spring:
  application:
    name: meu-dinheiro-api


  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

  flyway:
      enabled: true
      locations: classpath:db/migration
      baseline-on-migrate: false
      validate-on-migrate: true
  web:
    error:
      include-stacktrace: never
      include-message: never

server:
  port: 8080
