name: CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 25
        uses: actions/setup-java@v4
        with:
          distribution: graalvm
          java-version: '25'
          cache: maven

      - name: Grant execute permission for Maven Wrapper
        run: chmod +x mvnw

      - name: Build
        run: ./mvnw clean compile

      - name: Lint
        run: ./mvnw spotless:check

      - name: Architecture tests
        run: ./mvnw test -Parch

      - name: Unit tests
        run: ./mvnw test

      - name: Integration tests
        run: ./mvnw test-compile failsafe:integration-test failsafe:verify
